---
name: Install node_modules

inputs:

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Cache NPM
      uses: actions/cache@v3
      id: npm-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install node_modules
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: |
        unset NPM_CONFIG_USER
        npm ci
