name: Deploy to DigitalOcean

on:
  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:   
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.DO_SSHKEY }}
          passphrase: ${{ secrets.DO_SSHKEYPASS }}
          script: |
            cd Projects/raxee-bot
            git pull
            docker compose up -d --build
