---
name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  npm-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/npm-ci.yml

  lint:
    needs:
      - npm-ci
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/npm-ci.yml
      - name: Run lint
        run: npm run lint

  compile:
    needs:
      - npm-ci
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/npm-ci.yml
      - name: Run compile
        run: npm run compile

  test:
    needs:
      - npm-ci
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/npm-ci.yml
      - name: Run test
        run: npm run test
